apiVersion: v1
kind: Service
metadata:
  name: feedback-server-service-$VERSION
spec:
  type: ClusterIP
  selector:
    subsystem: feedback-server-$VERSION
  ports:
    - port: 4003 (CHANGE IF YOU WISH SO)
      targetPort: 3000
