apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: feedback-database-persistent-volume-claim-$VERSION
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
